/**
 * AUTO-GENERATED by scripts/generate-mode-registry.mjs — do not edit by hand.
 * Metadata-only catalog (no mode implementation imports).
 * Split into partitions (registryCatalog.partN.ts) to keep each file small;
 * this barrel re-assembles the full ordered list.
 */
import type { ModeCatalogEntry } from './registry';
import { MODE_CATALOG_PART_1 } from './registryCatalog.part1';
import { MODE_CATALOG_PART_2 } from './registryCatalog.part2';
import { MODE_CATALOG_PART_3 } from './registryCatalog.part3';
import { MODE_CATALOG_PART_4 } from './registryCatalog.part4';
import { MODE_CATALOG_PART_5 } from './registryCatalog.part5';

export const MODE_CATALOG: ModeCatalogEntry[] = [
  ...MODE_CATALOG_PART_1,
  ...MODE_CATALOG_PART_2,
  ...MODE_CATALOG_PART_3,
  ...MODE_CATALOG_PART_4,
  ...MODE_CATALOG_PART_5,
];
