#!/usr/bin/env bash
#
# build-webllm.sh
#
# Builds the ford442/web-llm fork from 3rd_party/web-llm and stages importable
# artifacts under 3rd_party/web-llm-dist/ for USE_CUSTOM_WEBLLM=1 consumption.
#
# Usage:
#   ./scripts/build-webllm.sh
#   SKIP_PATCHES=1 ./scripts/build-webllm.sh    # skip patches/web-llm/*.patch
#   SKIP_SUBMODULE_RESET=1 ./scripts/build-webllm.sh
#
# Rebase procedure: docs/webllm-rebase.md

set -euo pipefail

SUBMODULE_DIR="3rd_party/web-llm"
DIST_DIR="3rd_party/web-llm-dist"
PATCHES_DIR="patches/web-llm"
APPLIED_DIR="$PATCHES_DIR/.applied"
SCRIPT_NAME="$(basename "$0")"

if [[ -t 1 && -z "${NO_COLOR:-}" ]]; then
  RED='\033[0;31m'
  GREEN='\033[0;32m'
  YELLOW='\033[1;33m'
  BLUE='\033[0;34m'
  NC='\033[0m'
else
  RED='' GREEN='' YELLOW='' BLUE='' NC=''
fi

log() { echo -e "${BLUE}[webllm-build]${NC} $*"; }
warn() { echo -e "${YELLOW}[webllm-build] WARNING:${NC} $*" >&2; }
error() { echo -e "${RED}[webllm-build] ERROR:${NC} $*" >&2; exit 1; }

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

log "Starting custom web-llm build"

[[ -d "$SUBMODULE_DIR" ]] || error "Missing $SUBMODULE_DIR — run: git submodule update --init"
[[ -f "$SUBMODULE_DIR/package.json" ]] || error "$SUBMODULE_DIR/package.json missing"

command -v node >/dev/null 2>&1 || error "Node.js 18+ required"
NODE_MAJOR=$(node --version | sed 's/v//' | cut -d. -f1)
(( NODE_MAJOR >= 18 )) || error "Node.js 18+ required (found $(node --version))"
log "Node $(node --version), npm $(npm --version)"

pushd "$SUBMODULE_DIR" >/dev/null

if [[ "${SKIP_SUBMODULE_RESET:-0}" != "1" ]]; then
  log "Resetting submodule to committed SHA (clean slate for patches)"
  git reset --hard HEAD
  git clean -fd
fi

if [[ -d "lib" ]]; then
  log "Removing previous lib/ inside submodule"
  rm -rf lib
fi

if [[ -f "package-lock.json" ]]; then
  log "npm ci in submodule..."
  npm ci --no-audit --no-fund
else
  warn "No package-lock.json — falling back to npm install"
  npm install --no-audit --no-fund
fi

SUBMODULE_SHA=$(git rev-parse HEAD)
APPLIED_LIST=""

if [[ "${SKIP_PATCHES:-0}" != "1" && -d "../../$PATCHES_DIR" ]]; then
  mkdir -p "../../$APPLIED_DIR"
  shopt -s nullglob
  patches=(../../"$PATCHES_DIR"/*.patch)
  if ((${#patches[@]} > 0)); then
    log "Applying ${#patches[@]} patch(es) from $PATCHES_DIR"
    for patch in "${patches[@]}"; do
      base=$(basename "$patch")
      marker="../../$APPLIED_DIR/${base}.${SUBMODULE_SHA}.applied"
      if [[ -f "$marker" && "${FORCE_PATCHES:-0}" != "1" ]]; then
        log "  Skipping $base (already applied for $SUBMODULE_SHA)"
        APPLIED_LIST+="$base (cached); "
        continue
      fi
      log "  Applying $base"
      if git apply --check "$patch" 2>/dev/null; then
        git apply "$patch"
      elif patch -p1 --dry-run < "$patch" >/dev/null 2>&1; then
        patch -p1 < "$patch"
      else
        error "Patch $base failed --check. Rebase patches (see docs/webllm-rebase.md)."
      fi
      date -u +"%Y-%m-%dT%H:%M:%SZ" > "$marker"
      APPLIED_LIST+="$base; "
    done
  else
    log "No patches in $PATCHES_DIR"
  fi
  shopt -u nullglob
else
  log "Skipping patches (SKIP_PATCHES=1 or no patches dir)"
fi

log "npm run build (rollup + cleanup)..."
npm run build

popd >/dev/null

[[ -d "$SUBMODULE_DIR/lib" ]] || error "Build succeeded but $SUBMODULE_DIR/lib is missing"

log "Staging artifacts to $DIST_DIR"
rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"
echo "# Generated by $SCRIPT_NAME — see BUILD_INFO.txt" > "$DIST_DIR/.gitkeep"
cp -r "$SUBMODULE_DIR/lib" "$DIST_DIR/"
cp "$SUBMODULE_DIR/package.json" "$DIST_DIR/"

{
  echo "web-llm custom build for the_jokesters"
  echo "Build time:      $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "Submodule SHA:   $SUBMODULE_SHA"
  echo "Git describe:    $(cd "$SUBMODULE_DIR" && git describe --tags --always 2>/dev/null || echo no-tag)"
  echo "Node version:    $(node --version)"
  echo "npm version:     $(npm --version)"
  echo "Builder:         $SCRIPT_NAME"
  echo "Patches applied: ${APPLIED_LIST:-none}"
  echo "USE_CUSTOM_WEBLLM=1 to consume via vite alias"
} > "$DIST_DIR/BUILD_INFO.txt"

log "Artifact sizes:"
du -sh "$DIST_DIR"
TOTAL_JS_BYTES=$(find "$DIST_DIR/lib" -name "*.js" -exec cat {} + | wc -c | tr -d ' ')
log "Total JS (unminified): $(( TOTAL_JS_BYTES / 1024 )) KiB"

echo ""
echo -e "${GREEN}✓ Custom web-llm build complete → $DIST_DIR${NC}"
echo "Enable in the app: USE_CUSTOM_WEBLLM=1 npm run dev"
echo "See docs/webllm-rebase.md to sync with upstream mlc-ai/web-llm."

exit 0
